### PR TITLE
Bugs/3 renderhead

### LINKED ISSUE #3: Opening treetable item doesn't bind AJAX events to DOM nodes
Clicking on a TreeTableItem to open it and render its child nodes works partially: the child nodes are rendered, but the AJAX links' events are not bound to a Wicket handler.

See https://github.com/wicketstuff/wicket1.5-tree/blob/2616384c4333e9770b6671bc78d15edef72d0788/src/test/java/org/apache/wicket/extensions/markup/html/tree/TreeTablePageTest.java for a test case that illustrates this.

### PR DESCRIPTION
**Pull request by duesenklipper**
This fixes #3 by turning `AbstractTree$TreeItem#renderHead` into `internalRenderHead` as it should have been.

I also reverted the project to Java 7, because inmethod-grid works with 7, and the code in here doesn't really need Java 8.

What can I do to have this jar released and inmethod-grid updated as well?

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1,12 +1,14 @@
...
-# Mobile Tools for Java (J2ME)
-.mtj.tmp/
-
-# Package Files #
-*.jar
-*.war
-*.ear
-
-# virtual machine crash logs, see http://www.java.com/en/download/help/error_hotspot.xml
-hs_err_pid*
```
Comment (martin-g) [inline .gitignore:12]: Why the old entries are removed ?

File: src/main/java/org/apache/wicket/extensions/markup/html/tree/AbstractTree.java [hunk 2]
```diff
@@ -55,6 +40,13 @@
 import org.apache.wicket.util.visit.IVisit;
 import org.apache.wicket.util.visit.IVisitor;
 
+import javax.swing.event.TreeModelEvent;
+import javax.swing.event.TreeModelListener;
+import javax.swing.tree.TreeModel;
+import javax.swing.tree.TreeNode;
+import java.io.Serializable;
+import java.util.*;
```
Comment (martin-g) [inline src/main/java/org/apache/wicket/extensions/markup/html/tree/AbstractTree.java]: Please don't use `*` imports.

File: src/main/java/org/apache/wicket/extensions/markup/html/tree/AbstractTree.java [hunk 3]
```diff
@@ -264,9 +256,8 @@ public Object getModelObject()
 		}
 
 		@Override
-		public void renderHead(final IHeaderResponse response)
-		{
-			super.renderHead(response);
+		public void internalRenderHead(final HtmlHeaderContainer container) {
```
Comment (martin-g) [inline src/main/java/org/apache/wicket/extensions/markup/html/tree/AbstractTree.java:267]: Why `internalRenderHead()` is the correct thing to do ?
It is not clear from your description.

**Comment by martin-g** [comment]
Looks good to me.
Please address the small issues and I'll merge it and release it.

File: .gitignore (hunk 1 above)
Comment (duesenklipper) [inline .gitignore:12]: Because I was tired and just copied the .gitignore from wicketstuff-core without thinking. Re-adding those lines now.

File: src/main/java/org/apache/wicket/extensions/markup/html/tree/AbstractTree.java (hunk 3 above)
Comment (duesenklipper) [inline src/main/java/org/apache/wicket/extensions/markup/html/tree/AbstractTree.java:267]: Up to Wicket 6 we had renderHead(IHeaderResponse) for components to add their own header items, and we had renderHead(HtmlHeaderContainer) which handled calling the first method as well as collecting the header items from the component's behaviors.

AbstractTree$TreeItem in Wicket 6 overrode renderHead(HtmlHeaderContainer) to also collect the header items from the TreeItem's children to optimize render times (Not sure how much sense this makes nowadays, but I didn't want to change it).

In the transition to Wicket 7 and the move to this repo here, this was changed to renderHead(IHeaderResponse). That was wrong, because that method does _not_ handle behaviors - this is the reason that AjaxLinks didn't work, because their AjaxEventBehaviors were not called to add the appropriate header items.

The method renderHead(HtmlHeaderContainer) in Wicket 6 was renamed to internalRenderHead() in Wicket 7, since it really is internal and normally components shouldn't call or override it.

However, AbstractTree has always overridden this and actually relies on it to do its special child-rendering - basically it emulates some behavior from (I think) MarkupContainer to not just render itself but also its children.

Any component needs to have its internalRenderHead() called so its behaviors will be able to add header items, and since AbstractTree does special rendering logic for Ajax updates, it also needs to do this.

File: src/main/java/org/apache/wicket/extensions/markup/html/tree/AbstractTree.java (hunk 2 above)
Comment (duesenklipper) [inline src/main/java/org/apache/wicket/extensions/markup/html/tree/AbstractTree.java]: Fixed.

**Comment by martin-g** [comment]
7.1.0 has been released and is on its way to Maven Central!

**Comment by duesenklipper** [comment]
Awesome! Should I do a PR for the updated dependency in wicketstuff-core?

**Comment by martin-g** [comment]
Yup!
